language: go
go: 
  - 1.1
  - tip
script: go test -gocheck.v .
notificaitons:
  email:
    recipients:
      jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
  - go get -v launchpad.net/gocheck
